apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
type: Opaque
stringData:
  bootstrap.servers: <BOOTSTRAP_SERVER>
  security.protocol: SASL_SSL
  sasl.mechanism: PLAIN
  sasl.jaas.config: >-
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="<API_KEY>"
    password="<API_SECRET>";