apiVersion: v1
kind: Service
metadata:
  name: cst-example-flink-nodeport
spec:
  type: NodePort
  selector:
    app: cst-example  # Match the pod's label
  ports:
    - port: 8081           # The port exposed by the service
      targetPort: 8081      # The port that the container is listening on
      nodePort: 32081       # Optional: If you don't specify, Kubernetes will choose a random port in the range 30000-32767
      # make sure this port is allowed in security group
